services:
  - type: web
    name: vehicle-control
    runtime: python
    buildCommand: poetry install
    startCommand: poetry run streamlit run app.py --server.port $PORT --server.address 0.0.0.0
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000 