services:
  - type: web
    name: vehicle-control
    runtime: python
    buildCommand: |
      python -m pip install --upgrade pip
      pip install wheel
      pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.maxUploadSize 200 --server.enableCORS false --server.enableXsrfProtection true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: PORT
        value: 10000
      - key: STREAMLIT_SERVER_MAX_UPLOAD_SIZE
        value: 200
      - key: STREAMLIT_SERVER_ADDRESS
        value: 0.0.0.0
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"
    healthCheckPath: /
    autoDeploy: true
    plan: free 